@startuml umlactivity

title Бронювання заняття
header Доріжка

|Учень|
|Система|
|Репетитор|

|Учень|
start
:Обрати вільний слот у\nрозкладі;

|Система|
if (Слот доступний?) then ([так])
  :Створити запис\nбронювання зі\nстатусом "pending";
  :Надіслати сповіщення\nрепетитору;
  :Сповіщення "Нове\nбронювання">
  
  |Репетитор|
  :Сповіщення "Слот\nвже зайнятий"<
  :Прочитати сповіщення;
  :Встановити статус\nбронювання;
  
  |Система|
  if (Статус\nбронювання?) then ([confirmed])
    fork
      :Надіслати сповіщення\nучню;
      :Сповіщення "Бронювання\nпідтверджено">
      
      |Учень|
      :Сповіщення "Бронювання\nпідтверджено"<
      :Прочитати сповіщення;
    fork again
      |Система|
      :Позначити слот як\n"недоступний";
    end fork
    stop
  else ([cancelled])
    :Надіслати сповіщення\nучню;
    :Сповіщення "Бронювання\nвідхилено">
    
    |Учень|
    :Сповіщення "Бронювання\nвідхилено"<
    :Прочитати сповіщення;
    
    if (Обрати інший слот?) then (так)
    else (ні)
    stop
    endif
  endif
else ([ні])
  :Надіслати сповіщення\nучню;
  :Сповіщення "Слот\nвже зайнятий">
  
  |Учень|
  :Сповіщення "Слот\nвже зайнятий"<
  :Прочитати сповіщення;
  
  if (Обрати інший слот?) then (ні)
    stop
  else (так)
  endif
endif

@enduml